project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Work.qmd
        text: Relevant Work
      
    right: 
      - icon: github
        menu:
          - text: Website Source Code
            url:  https://github.com/seungjinni/personal-website
          - text: Github Profile
            url:  https://github.com/seungjinni
  page-footer:
    right: "&copy; 2024, Matthew Woo"
  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
    
execute:
  freeze: auto


