# Professional Exprience

*United States Army Reserve*

Enlisted Soldier \hfill January 2019 – January 2025

- Implemented tactics, procedures, and techniques for the defense system \
- Performed as a fire team member during situational training exercises and infantry-dismounted battle drills \
- Coordinated with unit leadership and direct superiors for taskings and managed subordinates to execute \

*National Assembly of the Republic of Korea* 

Legislative Assistant Internship \hfill June 2022 – August 2022

- Provided administrative and research support to Kim Mi Ae, a member of the congress on her parliamentary activities including bills, committee meetings, hearings, civil complaints related to central ministries, budget settlements, and public debates \
- Organized over 50 legislative proposals from the congress member over 2 years and recorded summaries of each proposal up-to-date utilizing Microsoft Office \
- Assisted in drafting and editing speeches including a press release on securing and supporting the implementation of child support expenses \